name: release
on:
  push:
    branches:
      - "!**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch: ~

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: release docker image
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          make build-docker-image
          make push-docker-image
